import NotFound from '../pages/404Page';
import AccessMent from '../pages/accessment';
import Attendance from '../pages/attendance';
import AttendanceInfo from '../pages/attendanceInfo';
import DashBoard from '../pages/dashboard';
import Department from '../pages/department';
import Level from '../pages/level';
import RewardRecord from '../pages/rewardRecord';
import Salary from '../pages/salary';
