export default [
  {
    path: "/dashboard",
    name: "dashboard",
    label: "员工分析",
    icon: "HomeOutlined",
    url: "/dashboard",
  },
  {
    path: "/attendanceInfo",
    name: "attendanceInfo",
    label: "出勤统计",
    icon: "CalendarOutlined",
    url: "/attendanceInfo",
  },
  {
    path: "/staff",
    name: "staff",
    label: "员工",
    icon: "TeamOutlined",
    url: "/staff",
  },
  {
    path: "/department",
    name: "department",
    label: "部门",
    icon: "PartitionOutlined",
    url: "/department",
  },
  {
    path: "/level",
    name: "level",
    label: "职级",
    icon: "ToTopOutlined",
    url: "/level",
  },
  {
    path: "/accessment",
    name: "accessment",
    label: "绩效考核",
    icon: "ContainerOutlined",
    url: "/accessment",
  },
  {
    path: "/salary",
    name: "salary",
    label: "调薪记录",
    icon: "MoneyCollectOutlined",
    url: "/salary",
  },
  {
    path: "/attendance",
    name: "attendance",
    label: "考勤管理",
    icon: "ClockCircleOutlined",
    url: "/attendance",
  },

  {
    path: "/rewardRecord",
    name: "rewardRecord",
    label: "奖励记录",
    icon: "ProjectOutlined",
    url: "/rewardRecord",
  },
];
